import { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import Products from "@/components/Products";
import { data } from "@/data";
import Search from "@/components/Search";
import Select from "@/components/Select";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState(data);
  const [searchTerm, setSearchTerm] = useState("");
  const [filteredProducts, setFilteredProducts] = useState(products);

  const filterName = filteredProducts.filter((item) => {
    if (item.name.toLowerCase().includes(searchTerm)) {
      return item;
    }
  });

  return (
    <>
      <Head>
        <title>Shoe Zone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Search searchWord={setSearchTerm} />
      <Select products={filterName} setFilteredProducts={setFilteredProducts} />
      <div className='md:max-w-6xl md:mx-auto'>
        <Products products={filterName} />
      </div>
    </>
  );
}
